# Workflow name
name: 🚀 Deploy website on push

# Event
on:
  push:
    branches:
      - main
      

# Actions
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: hera.fhict.nl
        username: i484704
        password: ${{ secrets.ftp_password }}
        server-dir: /domains/i482520.hera.fhict.nl/private_html/
